"""
Pydantic schemas for the LLM Alignment System pipeline.

These schemas are the data contracts between every stage of the pipeline:

    DatasetOrchestrator → SFTExample, DPOExample
    SFTTrainer          ← SFTExample (via preprocessor)
    DPOTrainer          ← DPOExample
    EvaluationPipeline  → ModelPrediction, EvaluationResult
    Comparator          ← BenchmarkResult
    ModelRegistry       ← ModelCheckpointMetadata
    WandB               ← ExperimentConfig

Design principles:
    1. Every field has a type. No bare `dict` or `Any` fields.
    2. Optional fields use `Optional[T] = None`, not missing keys.
    3. Enums for all categorical values — prevents silent string typos.
    4. Validators enforce invariants that cannot be expressed by types alone.
    5. Every schema has a `to_dict()` convenience method for JSON serialisation
       that handles non-serialisable types (datetime, enum, Path).

Local / cloud portability:
    All schemas are pure Python dataclass-equivalents. No GPU, no CUDA,
    no model loading. Import and use anywhere in the pipeline.
"""
from __future__ import annotations

import json
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────────────────────
# Enumerations
# Using Enum rather than Literal for values that appear in multiple schemas.
# This ensures the string "sft" in SFTExample and "sft" in ExperimentConfig
# are the same value, not two independently-typed string literals.
# ─────────────────────────────────────────────────────────────────────────────

class Role(str, Enum):
    """Valid roles in a conversational message turn."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ConversationQuality(str, Enum):
    """
    Provenance classification for SFT training examples.

    Controls training data weighting and quality-stratified ablations.
    HUMAN_WRITTEN > SYNTHETIC_LLM > SYNTHETIC_TEMPLATE in quality order.
    """
    HUMAN_WRITTEN = "human_written"           # Human-authored ground truth
    SYNTHETIC_LLM = "synthetic_llm"           # Generated by a stronger LLM
    SYNTHETIC_TEMPLATE = "synthetic_template" # Generated by code templates


class TaskType(str, Enum):
    """
    Task taxonomy for the alignment system.

    Used to route examples to the correct evaluator and to compute
    per-task breakdown statistics in benchmark results.
    """
    INSTRUCTION_FOLLOWING = "instruction_following"
    STRUCTURED_EXTRACTION = "structured_extraction"
    TOOL_CALLING = "tool_calling"
    SUMMARISATION = "summarisation"
    QUESTION_ANSWERING = "question_answering"
    REASONING = "reasoning"
    ALIGNMENT_EVAL = "alignment_eval"         # For red-teaming / safety evals
    OPEN_ENDED = "open_ended"


class DifficultyLevel(str, Enum):
    """
    Difficulty classification used for stratified evaluation reporting.
    adversarial examples stress model robustness.
    """
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    ADVERSARIAL = "adversarial"


class RejectionStrategy(str, Enum):
    """
    How a DPO rejected response was generated.

    Tracking this enables ablation studies on rejection strategy diversity:
    - Does mixing strategies outperform a single strategy?
    - Which strategy provides the most alignment signal?
    - Are certain failure modes more common in production?
    """
    HALLUCINATED_FIELDS = "hallucinated_fields"   # Added facts not in source
    SCHEMA_VIOLATION = "schema_violation"         # Wrong types / missing keys
    TRUNCATED = "truncated"                       # Cut off before completion
    VERBOSE_WRAPPER = "verbose_wrapper"           # Correct content, wrong format
    WRONG_NULLS = "wrong_nulls"                   # Over-conservative extraction
    INCORRECT_TOOL = "incorrect_tool"             # Wrong tool selected
    UNSAFE_CONTENT = "unsafe_content"             # Harmful or biased output
    FACTUAL_ERROR = "factual_error"               # Incorrect factual claims
    INSTRUCTION_IGNORED = "instruction_ignored"   # Ignored system prompt
    HUMAN_REJECTED = "human_rejected"             # Human annotator preference


class FailureMode(str, Enum):
    """
    Categorical error taxonomy for evaluation result analysis.
    Multiple failure modes can apply to a single prediction.
    """
    FORMAT_ERROR = "format_error"             # Wrong output format
    FACTUAL_HALLUCINATION = "factual_hallucination"
    FIELD_HALLUCINATION = "field_hallucination"  # Extra schema fields invented
    SCHEMA_VIOLATION = "schema_violation"
    INSTRUCTION_IGNORED = "instruction_ignored"
    TRUNCATED_OUTPUT = "truncated_output"
    REFUSAL = "refusal"                       # Model refused to answer
    OFF_TOPIC = "off_topic"
    UNSAFE_OUTPUT = "unsafe_output"
    REPETITION = "repetition"
    NONE = "none"                             # No failure — used for clean passes


class ModelStage(str, Enum):
    """
    Which stage of the alignment pipeline produced a prediction.
    Used to label BenchmarkResult rows for the final comparison table.
    """
    BASE = "base"
    PROMPT_ENGINEERED = "prompt_engineered"
    SFT = "sft"
    DPO = "dpo"
    RLHF = "rlhf"


# ─────────────────────────────────────────────────────────────────────────────
# Core message and conversation primitives
# ─────────────────────────────────────────────────────────────────────────────

class MessageTurn(BaseModel):
    """
    A single turn in a multi-turn conversation.

    The atomic unit reused across SFTExample, DPOExample, and ModelPrediction.
    Keeping this as a separate model means chat format is defined once.

    Fields:
        role:      Who produced this message (system / user / assistant / tool).
        content:   The message text.
        turn_idx:  0-based position in the conversation (auto-assigned).
        metadata:  Optional unstructured metadata (tool call results, etc.).
    """
    role: Role
    content: str = Field(..., min_length=1)
    turn_idx: int = Field(default=0, ge=0)
    metadata: Optional[dict[str, Any]] = None

    @field_validator("content")
    @classmethod
    def content_not_whitespace_only(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message content cannot be whitespace only")
        return v


class Conversation(BaseModel):
    """
    An ordered sequence of MessageTurns forming a complete conversation.

    Validates that:
        - First turn is always system (alignment training convention).
        - Turns alternate user/assistant after the system prompt.
        - At least one user and one assistant turn are present.

    The `prompt_only` property returns all turns except the final assistant
    response — this is the prefix used for DPO and generation.
    """
    turns: list[MessageTurn] = Field(..., min_length=2)

    @model_validator(mode="after")
    def validate_turn_structure(self) -> "Conversation":
        roles = [t.role for t in self.turns]

        if roles[0] != Role.SYSTEM:
            raise ValueError(
                f"First turn must be 'system', got '{roles[0]}'"
            )
        if Role.USER not in roles:
            raise ValueError("Conversation must contain at least one user turn")
        if Role.ASSISTANT not in roles:
            raise ValueError(
                "Conversation must contain at least one assistant turn"
            )
        return self

    @property
    def system_prompt(self) -> str:
        """Return the system prompt text."""
        return self.turns[0].content

    @property
    def prompt_only(self) -> list[MessageTurn]:
        """Return all turns except the final assistant response."""
        if self.turns[-1].role == Role.ASSISTANT:
            return self.turns[:-1]
        return self.turns

    @property
    def final_response(self) -> Optional[str]:
        """Return the final assistant turn content, or None."""
        if self.turns[-1].role == Role.ASSISTANT:
            return self.turns[-1].content
        return None

    @property
    def num_user_turns(self) -> int:
        return sum(1 for t in self.turns if t.role == Role.USER)


# ─────────────────────────────────────────────────────────────────────────────
# SFT training schema
# ─────────────────────────────────────────────────────────────────────────────

class SFTExample(BaseModel):
    """
    One supervised fine-tuning training example.

    This is the primary data structure produced by DatasetOrchestrator
    and consumed by build_sft_datasets() → SFTDataCollator → SFTTrainer.

    Fields:
        example_id:    Unique identifier. Generated automatically if not set.
                       Used to join training examples with evaluation results.
        conversation:  The full conversation including the reference response.
        task_type:     Routing key for task-specific evaluation.
        difficulty:    Controls evaluation stratification.
        quality:       Provenance signal for training data weighting.
        source:        Free-form source description (e.g. "generated_invoice_v2").
        weight:        Sampling weight during training. Defaults to 1.0.
                       Set > 1.0 for HUMAN_WRITTEN examples, < 1.0 for
                       low-quality synthetic examples.
        created_at:    Generation timestamp for dataset versioning.
        tags:          Arbitrary labels for filtering (e.g. ["financial", "noisy"]).

    Properties:
        input_text:    The user message content (last user turn).
        target_text:   The reference assistant response (final turn content).
        system_prompt: The system prompt string.
    """
    example_id: str = Field(default_factory=lambda: str(uuid4()))
    conversation: Conversation
    task_type: TaskType
    difficulty: DifficultyLevel = DifficultyLevel.MEDIUM
    quality: ConversationQuality = ConversationQuality.SYNTHETIC_TEMPLATE
    source: str = Field(default="", description="Generator or dataset source identifier")
    weight: float = Field(default=1.0, ge=0.0, le=10.0)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    tags: list[str] = Field(default_factory=list)

    @property
    def system_prompt(self) -> str:
        return self.conversation.system_prompt

    @property
    def input_text(self) -> str:
        """
        Return the user-facing input text (last user turn).
        For multi-turn conversations, this is the final user message.
        """
        user_turns = [t for t in self.conversation.turns if t.role == Role.USER]
        if not user_turns:
            raise ValueError(f"SFTExample {self.example_id} has no user turns")
        return user_turns[-1].content

    @property
    def target_text(self) -> str:
        """
        Return the reference response (final assistant turn).
        This is the text the model must learn to produce.
        Raises if the conversation has no assistant turn.
        """
        response = self.conversation.final_response
        if response is None:
            raise ValueError(
                f"SFTExample {self.example_id} has no final assistant turn"
            )
        return response

    def to_dict(self) -> dict:
        return {
            "example_id": self.example_id,
            "turns": [
                {"role": t.role.value, "content": t.content}
                for t in self.conversation.turns
            ],
            "task_type": self.task_type.value,
            "difficulty": self.difficulty.value,
            "quality": self.quality.value,
            "source": self.source,
            "weight": self.weight,
            "created_at": self.created_at.isoformat(),
            "tags": self.tags,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SFTExample":
        """Deserialise from a dict (loaded from JSONL disk storage)."""
        turns = [
            MessageTurn(role=Role(t["role"]), content=t["content"], turn_idx=i)
            for i, t in enumerate(data["turns"])
        ]
        return cls(
            example_id=data.get("example_id", str(uuid4())),
            conversation=Conversation(turns=turns),
            task_type=TaskType(data["task_type"]),
            difficulty=DifficultyLevel(data.get("difficulty", "medium")),
            quality=ConversationQuality(
                data.get("quality", "synthetic_template")
            ),
            source=data.get("source", ""),
            weight=float(data.get("weight", 1.0)),
            tags=data.get("tags", []),
        )


# ─────────────────────────────────────────────────────────────────────────────
# DPO preference schema
# ─────────────────────────────────────────────────────────────────────────────

class DPOExample(BaseModel):
    """
    One Direct Preference Optimization training pair.

    TRL's DPOTrainer consumes this format directly (prompt, chosen, rejected).

    The schema extends TRL's minimal requirement with alignment research fields:
    - preference_strength: enables weighted DPO variants
    - rejection_strategy:  enables ablation on rejection diversity
    - alignment_signal:    captures reward / safety scores if available

    Fields:
        pair_id:            Unique identifier. Traceable back to sft_example_id.
        sft_example_id:     The SFTExample this pair was derived from.
        prompt:             Chat-template-formatted prompt string with generation
                            prefix applied (add_generation_prompt=True).
                            This is what DPOTrainer uses to locate response boundaries.
        chosen:             The preferred response string (no special tokens).
        rejected:           The dispreferred response string (no special tokens).
        preference_strength: Float [0, 1]. How confident we are in the preference.
                            0.5 = indeterminate, 1.0 = absolute.
                            Standard DPO treats all pairs as 1.0.
                            Weighted DPO uses this to scale the loss contribution.
        rejection_strategy: How the rejected response was generated.
        task_type:          Task routing key.
        difficulty:         Difficulty tier of the source example.
        created_at:         Generation timestamp.
    """
    pair_id: str = Field(default_factory=lambda: str(uuid4()))
    sft_example_id: Optional[str] = None
    prompt: str = Field(..., min_length=1)
    chosen: str = Field(..., min_length=1)
    rejected: str = Field(..., min_length=1)
    preference_strength: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Preference confidence: 0.5=indeterminate, 1.0=absolute",
    )
    rejection_strategy: RejectionStrategy = RejectionStrategy.HALLUCINATED_FIELDS
    task_type: TaskType = TaskType.INSTRUCTION_FOLLOWING
    difficulty: DifficultyLevel = DifficultyLevel.MEDIUM
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @model_validator(mode="after")
    def chosen_differs_from_rejected(self) -> "DPOExample":
        if self.chosen.strip() == self.rejected.strip():
            raise ValueError(
                f"DPO pair {self.pair_id}: chosen and rejected are identical. "
                "This pair provides no learning signal."
            )
        return self

    def to_trl_dict(self) -> dict[str, str]:
        """
        Return the minimal dict format consumed by TRL's DPOTrainer.
        TRL requires exactly these three keys.
        """
        return {
            "prompt": self.prompt,
            "chosen": self.chosen,
            "rejected": self.rejected,
        }

    def to_dict(self) -> dict:
        return {
            "pair_id": self.pair_id,
            "sft_example_id": self.sft_example_id,
            "prompt": self.prompt,
            "chosen": self.chosen,
            "rejected": self.rejected,
            "preference_strength": self.preference_strength,
            "rejection_strategy": self.rejection_strategy.value,
            "task_type": self.task_type.value,
            "difficulty": self.difficulty.value,
            "created_at": self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
# Model prediction schema
# ─────────────────────────────────────────────────────────────────────────────

class GenerationConfig(BaseModel):
    """
    The decoding configuration used for a specific inference call.
    Stored alongside predictions so results are fully reproducible.
    """
    max_new_tokens: int = Field(default=512, ge=1)
    temperature: float = Field(default=0.0, ge=0.0, le=2.0)
    do_sample: bool = False
    top_p: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    top_k: Optional[int] = Field(default=None, ge=1)
    repetition_penalty: float = Field(default=1.1, ge=1.0)
    num_beams: int = Field(default=1, ge=1)


class ModelPrediction(BaseModel):
    """
    The output of one model inference call.

    Stores everything needed to:
    1. Evaluate the prediction (generated_text + prompt + reference).
    2. Reproduce the inference (generation_config + model_stage + model_id).
    3. Diagnose issues (latency_ms + input_tokens + output_tokens).
    4. Re-evaluate with new metrics (predictions saved separately from results).

    Fields:
        prediction_id:     Unique identifier.
        example_id:        Links back to the SFTExample that produced this.
        model_id:          Model name or checkpoint path.
        model_stage:       Which pipeline stage generated this.
        prompt:            The full formatted prompt sent to the model.
        generated_text:    Raw text output from the model.
        reference_text:    Ground truth answer (for metric computation).
        task_type:         Task routing key.
        difficulty:        Difficulty tier.
        input_tokens:      Number of prompt tokens.
        output_tokens:     Number of generated tokens.
        latency_ms:        Wall-clock inference time in milliseconds.
        generation_config: Decoding parameters used.
        log_probs:         Optional per-token log probabilities.
                           Used for perplexity and reward signal computation.
        created_at:        Inference timestamp.
    """
    prediction_id: str = Field(default_factory=lambda: str(uuid4()))
    example_id: Optional[str] = None
    model_id: str = Field(..., min_length=1)
    model_stage: ModelStage
    prompt: str
    generated_text: str = Field(default="")
    reference_text: Optional[str] = None
    task_type: TaskType = TaskType.INSTRUCTION_FOLLOWING
    difficulty: DifficultyLevel = DifficultyLevel.MEDIUM
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    latency_ms: float = Field(default=0.0, ge=0.0)
    generation_config: GenerationConfig = Field(default_factory=GenerationConfig)
    log_probs: Optional[list[float]] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def tokens_per_second(self) -> float:
        if self.latency_ms <= 0:
            return 0.0
        total = self.input_tokens + self.output_tokens
        return round(total / (self.latency_ms / 1000), 1)

    @property
    def is_empty(self) -> bool:
        return len(self.generated_text.strip()) == 0

    def to_dict(self) -> dict:
        return {
            "prediction_id": self.prediction_id,
            "example_id": self.example_id,
            "model_id": self.model_id,
            "model_stage": self.model_stage.value,
            "prompt": self.prompt,
            "generated_text": self.generated_text,
            "reference_text": self.reference_text,
            "task_type": self.task_type.value,
            "difficulty": self.difficulty.value,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "latency_ms": self.latency_ms,
            "tokens_per_second": self.tokens_per_second,
            "created_at": self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
# Evaluation schemas
# ─────────────────────────────────────────────────────────────────────────────

class AlignmentSignal(BaseModel):
    """
    Structured alignment quality signals for a single response.

    Used in evaluation and optionally in weighted DPO.
    Scores are floats in [0, 1] — 1.0 is optimal, 0.0 is worst.

    Fields:
        reward_score:       Scalar reward from a reward model or heuristic.
                            None if no reward model was used.
        safety_score:       Probability the response is safe/harmless.
        helpfulness_score:  Subjective helpfulness rating.
        honesty_score:      Whether claims are grounded and accurate.
        instruction_score:  Whether the response followed the instruction.
        is_harmful:         Hard flag — True triggers rejection regardless of scores.
        harm_categories:    Specific harm types detected if any.
    """
    reward_score: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    safety_score: float = Field(default=1.0, ge=0.0, le=1.0)
    helpfulness_score: float = Field(default=0.5, ge=0.0, le=1.0)
    honesty_score: float = Field(default=0.5, ge=0.0, le=1.0)
    instruction_score: float = Field(default=0.5, ge=0.0, le=1.0)
    is_harmful: bool = False
    harm_categories: list[str] = Field(default_factory=list)

    @property
    def composite_score(self) -> float:
        """
        Weighted composite of alignment dimensions.
        Safety is weighted highest because harm is non-negotiable.
        """
        return round(
            0.35 * self.safety_score
            + 0.25 * self.helpfulness_score
            + 0.25 * self.honesty_score
            + 0.15 * self.instruction_score,
            4,
        )


class EvaluationResult(BaseModel):
    """
    Evaluation metrics for one ModelPrediction against a reference.

    This is the output of one call to MetricsComputer.evaluate().
    Stored per-example so you can drill into individual failures.

    Fields:
        result_id:              Unique identifier.
        prediction_id:          Links back to the ModelPrediction.
        example_id:             Links back to the SFTExample.
        model_stage:            Which pipeline stage was evaluated.
        task_type:              Task routing key.
        difficulty:             Difficulty tier.
        exact_match:            Boolean — prediction == reference (normalised).
        format_valid:           Boolean — output is valid JSON / follows format.
        schema_compliant:       Boolean — output matches target Pydantic schema.
        instruction_followed:   Boolean — response respected the system prompt.
        hallucination_detected: Boolean — invented fields / facts detected.
        bleu:                   BLEU score against reference [0, 1].
        rouge_l:                ROUGE-L F1 against reference [0, 1].
        field_f1:               Token-level F1 across structured fields [0, 1].
        latency_ms:             Inference latency from the ModelPrediction.
        tokens_per_second:      Throughput from the ModelPrediction.
        failure_modes:          Categorical error labels for this example.
        alignment_signal:       Optional alignment quality scores.
    """
    result_id: str = Field(default_factory=lambda: str(uuid4()))
    prediction_id: Optional[str] = None
    example_id: Optional[str] = None
    model_stage: ModelStage
    task_type: TaskType
    difficulty: DifficultyLevel

    # Core alignment metrics
    exact_match: bool = False
    format_valid: bool = False
    schema_compliant: bool = False
    instruction_followed: bool = False
    hallucination_detected: bool = False

    # Lexical similarity metrics
    bleu: float = Field(default=0.0, ge=0.0, le=1.0)
    rouge_l: float = Field(default=0.0, ge=0.0, le=1.0)
    field_f1: float = Field(default=0.0, ge=0.0, le=1.0)

    # Latency (copied from prediction for fast aggregation)
    latency_ms: float = Field(default=0.0, ge=0.0)
    tokens_per_second: float = Field(default=0.0, ge=0.0)

    # Failure analysis
    failure_modes: list[FailureMode] = Field(default_factory=list)
    failure_notes: Optional[str] = None

    # Alignment signal
    alignment_signal: Optional[AlignmentSignal] = None

    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def passed(self) -> bool:
        """True if the prediction meets the minimum acceptance bar."""
        return self.format_valid and not self.hallucination_detected

    @property
    def alignment_score(self) -> float:
        """
        Composite alignment score for ranking purposes.
        Weights instruction following and hallucination avoidance highest.
        """
        return round(
            0.25 * float(self.format_valid)
            + 0.25 * float(self.instruction_followed)
            + 0.20 * float(not self.hallucination_detected)
            + 0.15 * self.field_f1
            + 0.10 * self.rouge_l
            + 0.05 * float(self.exact_match),
            4,
        )

    def to_dict(self) -> dict:
        return {
            "result_id": self.result_id,
            "prediction_id": self.prediction_id,
            "example_id": self.example_id,
            "model_stage": self.model_stage.value,
            "task_type": self.task_type.value,
            "difficulty": self.difficulty.value,
            "exact_match": self.exact_match,
            "format_valid": self.format_valid,
            "schema_compliant": self.schema_compliant,
            "instruction_followed": self.instruction_followed,
            "hallucination_detected": self.hallucination_detected,
            "bleu": self.bleu,
            "rouge_l": self.rouge_l,
            "field_f1": self.field_f1,
            "latency_ms": self.latency_ms,
            "tokens_per_second": self.tokens_per_second,
            "alignment_score": self.alignment_score,
            "failure_modes": [f.value for f in self.failure_modes],
            "failure_notes": self.failure_notes,
            "passed": self.passed,
            "created_at": self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
# Benchmark aggregation schemas
# ─────────────────────────────────────────────────────────────────────────────

class TaskMetrics(BaseModel):
    """Aggregated metrics for a single task type within a benchmark run."""
    task_type: TaskType
    n_examples: int = 0
    exact_match: float = 0.0
    format_valid: float = 0.0
    schema_compliant: float = 0.0
    instruction_followed: float = 0.0
    hallucination_rate: float = 0.0
    avg_bleu: float = 0.0
    avg_rouge_l: float = 0.0
    avg_field_f1: float = 0.0
    avg_alignment_score: float = 0.0
    avg_latency_ms: float = 0.0


class DifficultyMetrics(BaseModel):
    """Aggregated metrics for a single difficulty tier within a benchmark run."""
    difficulty: DifficultyLevel
    n_examples: int = 0
    format_valid: float = 0.0
    instruction_followed: float = 0.0
    hallucination_rate: float = 0.0
    avg_alignment_score: float = 0.0


class BenchmarkResult(BaseModel):
    """
    Aggregated evaluation metrics for one complete benchmark run.

    This is the primary output of EvaluationPipeline.run() and the
    data structure stored in metrics/sft_metrics.json, metrics/dpo_metrics.json.

    One BenchmarkResult per model stage per evaluation run.
    ModelComparator reads multiple BenchmarkResults to produce the
    final comparison table (Base → Prompt → SFT → DPO).

    Fields:
        run_id:                 Unique identifier for this benchmark run.
        model_id:               Model name or checkpoint path.
        model_stage:            Pipeline stage label.
        n_examples:             Total examples evaluated.
        n_tasks:                Number of distinct tasks evaluated.
        exact_match:            Fraction where prediction == reference.
        format_valid:           Fraction with valid output format.
        schema_compliant:       Fraction passing schema validation.
        instruction_followed:   Fraction following the system prompt.
        hallucination_rate:     Fraction with hallucinated content.
        avg_bleu:               Mean BLEU across all examples.
        avg_rouge_l:            Mean ROUGE-L F1 across all examples.
        avg_field_f1:           Mean token-level field F1.
        avg_alignment_score:    Mean composite alignment score.
        avg_latency_ms:         Mean inference latency.
        p95_latency_ms:         95th percentile inference latency.
        avg_tokens_per_second:  Mean throughput.
        by_task:                Per-task breakdown.
        by_difficulty:          Per-difficulty breakdown.
        failure_mode_counts:    Counts of each failure mode category.
        evaluated_at:           Timestamp.
    """
    run_id: str = Field(default_factory=lambda: str(uuid4()))
    model_id: str
    model_stage: ModelStage
    n_examples: int = 0
    n_tasks: int = 0

    # Global metrics (all tasks, all difficulties)
    exact_match: float = Field(default=0.0, ge=0.0, le=1.0)
    format_valid: float = Field(default=0.0, ge=0.0, le=1.0)
    schema_compliant: float = Field(default=0.0, ge=0.0, le=1.0)
    instruction_followed: float = Field(default=0.0, ge=0.0, le=1.0)
    hallucination_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_bleu: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_rouge_l: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_field_f1: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_alignment_score: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_latency_ms: float = Field(default=0.0, ge=0.0)
    p95_latency_ms: float = Field(default=0.0, ge=0.0)
    avg_tokens_per_second: float = Field(default=0.0, ge=0.0)

    # Stratified breakdowns
    by_task: dict[str, TaskMetrics] = Field(default_factory=dict)
    by_difficulty: dict[str, DifficultyMetrics] = Field(default_factory=dict)
    failure_mode_counts: dict[str, int] = Field(default_factory=dict)

    evaluated_at: datetime = Field(default_factory=datetime.utcnow)

    def summary(self) -> str:
        """
        Human-readable one-line summary for logging.
        Suitable for printing at the end of a training or evaluation run.
        """
        return (
            f"[{self.model_stage.value.upper()}] "
            f"format={self.format_valid * 100:.1f}% | "
            f"instr={self.instruction_followed * 100:.1f}% | "
            f"halluc={self.hallucination_rate * 100:.1f}% | "
            f"align={self.avg_alignment_score * 100:.1f}% | "
            f"lat={self.avg_latency_ms:.0f}ms | "
            f"n={self.n_examples}"
        )

    def to_dict(self) -> dict:
        d = self.model_dump()
        d["model_stage"] = self.model_stage.value
        d["by_task"] = {
            k: v.model_dump(mode="json") for k, v in self.by_task.items()
        }
        d["by_difficulty"] = {
            k: v.model_dump(mode="json") for k, v in self.by_difficulty.items()
        }
        d["evaluated_at"] = self.evaluated_at.isoformat()
        return d

    def delta_vs(self, baseline: "BenchmarkResult") -> dict[str, float]:
        """
        Compute percentage-point improvement over a baseline BenchmarkResult.
        Positive = improvement. Used in the final comparison table.
        """
        metrics = [
            "format_valid", "schema_compliant", "instruction_followed",
            "avg_alignment_score", "avg_field_f1", "avg_rouge_l",
        ]
        deltas: dict[str, float] = {}
        for m in metrics:
            self_val = getattr(self, m, 0.0)
            base_val = getattr(baseline, m, 0.0)
            deltas[f"{m}_delta_pp"] = round((self_val - base_val) * 100, 2)

        # For hallucination and latency, improvement means reduction
        deltas["hallucination_rate_delta_pp"] = round(
            (baseline.hallucination_rate - self.hallucination_rate) * 100, 2
        )
        deltas["latency_delta_ms"] = round(
            baseline.avg_latency_ms - self.avg_latency_ms, 1
        )
        return deltas


# ─────────────────────────────────────────────────────────────────────────────
# Dataset and experiment metadata schemas
# ─────────────────────────────────────────────────────────────────────────────

class DatasetSplit(BaseModel):
    """
    Metadata and quality statistics for one dataset split.

    Written by generate_dataset.py, read by training scripts to verify
    the dataset before spending compute on training.
    """
    split_name: Literal["train", "validation", "test"]
    n_examples: int = Field(..., ge=0)
    by_task: dict[str, int] = Field(default_factory=dict)
    by_difficulty: dict[str, int] = Field(default_factory=dict)
    by_quality: dict[str, int] = Field(default_factory=dict)
    avg_input_chars: float = 0.0
    avg_output_chars: float = 0.0
    p95_input_chars: float = 0.0
    validity_pct: float = Field(default=100.0, ge=0.0, le=100.0)
    path: str = ""


class DatasetMetadata(BaseModel):
    """
    Complete metadata record for the generated dataset.
    The dataset's birth certificate — stores generation provenance.

    Stored at: data/processed/metadata.json
    Read by:   training scripts (to verify dataset before training),
               evaluation scripts (to confirm train/test split boundaries),
               experiment tracking (logged to W&B as a config artifact).
    """
    dataset_id: str = Field(default_factory=lambda: str(uuid4()))
    version: str = "1.0.0"
    total_examples: int = 0
    splits: dict[str, DatasetSplit] = Field(default_factory=dict)
    dpo_pairs: int = 0
    seed: int = 42
    generation_config: dict[str, Any] = Field(default_factory=dict)
    validation_report: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    generator_version: str = "1.0.0"
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "dataset_id": self.dataset_id,
            "version": self.version,
            "total_examples": self.total_examples,
            "splits": {
                k: v.model_dump() for k, v in self.splits.items()
            },
            "dpo_pairs": self.dpo_pairs,
            "seed": self.seed,
            "generation_config": self.generation_config,
            "validation_report": self.validation_report,
            "created_at": self.created_at.isoformat(),
            "generator_version": self.generator_version,
            "notes": self.notes,
        }


class ModelCheckpointMetadata(BaseModel):
    """
    Registry record for a saved model checkpoint.

    Stored by: checkpointing.py after every save
    Read by:   model_registry.py, evaluation scripts, serve.py

    This schema answers the question: "which checkpoint is the best SFT
    model, and what training run produced it?"
    """
    checkpoint_id: str = Field(default_factory=lambda: str(uuid4()))
    model_stage: ModelStage
    base_model_id: str = Field(..., description="HuggingFace model name or path")
    adapter_path: str = Field(..., description="Path to saved PEFT adapter directory")
    merged_path: Optional[str] = None
    training_step: int = Field(..., ge=0)
    training_epoch: float = Field(..., ge=0)
    eval_loss: Optional[float] = None
    benchmark_result_id: Optional[str] = None
    trainable_params_M: Optional[float] = None
    lora_rank: Optional[int] = None
    lora_alpha: Optional[int] = None
    learning_rate: Optional[float] = None
    effective_batch_size: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_best: bool = False
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "checkpoint_id": self.checkpoint_id,
            "model_stage": self.model_stage.value,
            "base_model_id": self.base_model_id,
            "adapter_path": self.adapter_path,
            "merged_path": self.merged_path,
            "training_step": self.training_step,
            "training_epoch": self.training_epoch,
            "eval_loss": self.eval_loss,
            "trainable_params_M": self.trainable_params_M,
            "lora_rank": self.lora_rank,
            "lora_alpha": self.lora_alpha,
            "learning_rate": self.learning_rate,
            "is_best": self.is_best,
            "created_at": self.created_at.isoformat(),
            "notes": self.notes,
        }


class ExperimentConfig(BaseModel):
    """
    Complete configuration record for one training experiment.

    Logged to W&B at run start. Stored alongside checkpoint metadata.
    Enables reproducibility: given an ExperimentConfig, the full training
    run can be replicated from scratch.

    Fields grouped by concern:
        Identification:  experiment_id, run_name, description
        Model:           base_model_id, model_stage, lora_rank, lora_alpha,
                         target_modules, quantization_bits
        Training:        learning_rate, effective_batch_size, num_epochs,
                         warmup_ratio, weight_decay, lr_scheduler,
                         gradient_checkpointing, bf16
        Data:            dataset_id, dataset_version, train_size, max_seq_length
        Infrastructure:  device, gpu_name, num_gpus
    """
    experiment_id: str = Field(default_factory=lambda: str(uuid4()))
    run_name: str = Field(..., min_length=1)
    description: str = ""
    model_stage: ModelStage

    # Model config
    base_model_id: str
    lora_rank: Optional[int] = None
    lora_alpha: Optional[int] = None
    target_modules: list[str] = Field(default_factory=list)
    quantization_bits: Optional[int] = None

    # Training hyperparameters
    learning_rate: float = Field(..., gt=0)
    per_device_batch_size: int = Field(..., ge=1)
    gradient_accumulation_steps: int = Field(default=1, ge=1)
    num_epochs: float = Field(..., gt=0)
    warmup_ratio: float = Field(default=0.03, ge=0.0, le=1.0)
    weight_decay: float = Field(default=0.01, ge=0.0)
    lr_scheduler: str = "cosine"
    max_grad_norm: float = Field(default=1.0, gt=0)
    gradient_checkpointing: bool = True
    bf16: bool = True
    seed: int = 42

    # DPO-specific (None for SFT runs)
    dpo_beta: Optional[float] = Field(default=None, ge=0.0)
    dpo_loss_type: Optional[str] = None

    # Data
    dataset_id: Optional[str] = None
    dataset_version: str = "1.0.0"
    train_size: int = 0
    max_seq_length: int = 2048

    # Infrastructure
    device: str = "cuda"
    gpu_name: Optional[str] = None
    num_gpus: int = 1

    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def effective_batch_size(self) -> int:
        return self.per_device_batch_size * self.gradient_accumulation_steps * self.num_gpus

    def to_wandb_dict(self) -> dict[str, Any]:
        """
        Flatten config to a plain dict for W&B `wandb.init(config=...)`.
        W&B does not accept nested Pydantic models or datetime objects.
        """
        return {
            "experiment_id": self.experiment_id,
            "run_name": self.run_name,
            "model_stage": self.model_stage.value,
            "base_model_id": self.base_model_id,
            "lora_rank": self.lora_rank,
            "lora_alpha": self.lora_alpha,
            "lora_scale": (
                self.lora_alpha / self.lora_rank
                if self.lora_rank and self.lora_alpha else None
            ),
            "quantization_bits": self.quantization_bits,
            "learning_rate": self.learning_rate,
            "per_device_batch_size": self.per_device_batch_size,
            "gradient_accumulation_steps": self.gradient_accumulation_steps,
            "effective_batch_size": self.effective_batch_size,
            "num_epochs": self.num_epochs,
            "warmup_ratio": self.warmup_ratio,
            "weight_decay": self.weight_decay,
            "lr_scheduler": self.lr_scheduler,
            "max_grad_norm": self.max_grad_norm,
            "gradient_checkpointing": self.gradient_checkpointing,
            "bf16": self.bf16,
            "seed": self.seed,
            "dpo_beta": self.dpo_beta,
            "train_size": self.train_size,
            "max_seq_length": self.max_seq_length,
            "device": self.device,
            "gpu_name": self.gpu_name,
        }

    def to_dict(self) -> dict:
        d = self.to_wandb_dict()
        d["target_modules"] = self.target_modules
        d["dataset_id"] = self.dataset_id
        d["dataset_version"] = self.dataset_version
        d["created_at"] = self.created_at.isoformat()
        return d